name: CI/CD Pipeline

on:
    push:
        branches:
            - main
            - develop

permissions:
    contents: read
    packages: write

jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
            # 1️⃣ Checkout code
            - name: Checkout code
              uses: actions/checkout@v4

            # 2️⃣ Set up PHP (for testing)
            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  extensions: mbstring, pdo_mysql, intl
                  coverage: none

            # 3️⃣ Install dependencies
            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist --optimize-autoloader

            # 4️⃣ Run tests
            - name: Run tests
              run: php bin/phpunit --testdox

            # 5️⃣ Build Docker image
            - name: Build Docker image
              run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/symfony-app:latest .

            # 6️⃣ Login to Docker Hub
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            # 7️⃣ Push Docker image
            - name: Push Docker image
              run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/symfony-app:latest
